### ISSUE TITLE
Resistor changing

### ISSUE THREAD

**Issue by Nikhil123456789** [vikilabs-code/hombot-issues#215]
change 200 K (at shift out IC) with 240 K. if it is working properly than we can use 240 K instead of 200 K

**Comment by e-ve** [comment]
Good to go with 240K.It works as expected.

**Comment by e-ve** [comment]
Also updated the Document.

**Comment by e-ve** [comment]
@rallicknom  @Nikhil123456789  change the value on PCB files.

**Comment by rallicknom** [comment]
Changed the value in Hombot - 7 PCB.

@Nikhil123456789 - Keep in mind that you send the modified value for soldering from next time. Also take a look at other components in BOM and notify me if we can use one component instead of two in such cases. We will carry out the testing and change the values.

Closing the issue.
