### ISSUE TITLE
Test case for Extender with same name

### ISSUE THREAD

**Issue by battuashwik** [vikilabs-code/hombot-issues#90]

**Comment by bansaldhruv1** [comment]
@rallicknom can you verify this. Have Completed this.

**Comment by rallicknom** [comment]
Extenders with same SSID and password as source router was found to be working perfectly. ESP was connecting to extender the same way it would connect to the source router and seamless control via app was possible. After turning the extender off, the source router's SSID was present but since ESP wasn't able to connect to it due to weak signal, no control was possible. After turning the extender back ON, the control came back as expected.

One possible issue with extender setup: The coverage of an extender is quite less as compared to a router. As such too many extenders might be required for the same job that can be handled by a single router. This will increase the cost by a huge factor.
